// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggxbrxqpjafvytpdhxrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdneGJyeHFwamFmdnl0cGRoeHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDYxNDQsImV4cCI6MjA2NzMyMjE0NH0.CyouuQYeb3nsZ0xbrzC7sFF3bUl6MvgjqQnaRWiz3OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});